minimumReleaseAgeExclude:
  - '@kungfu-tech/buildchain@2.10.1 || 2.10.2 || 2.10.3 || 2.10.4 || 2.10.8 || 2.11.0 || 2.11.1'
  - '@kungfu-tech/kfd@1.0.0-alpha.16 || 1.0.0-alpha.19 || 1.0.0-alpha.21 || 1.0.0-alpha.22'
